import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ModeToggle } from "@/components/ld-toggle";
import Image from "next/image";
import Navbar from "@/components/global/Navbar";
import Footer from "@/components/global/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gerald Tay",
  description: "Generated by create next app",
  icons:{
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/images/light/favicon-32x32.png',
        href: '/images/light/favicon-32x32.png',
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/images/dark/favicon-32x32.png',
        href: '/images/dark/favicon-32x32.png',
      },
    ],
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-2xl">
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
          <Navbar/>
            {children}
          <footer>
           <Footer/>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
